inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance
  - rubocop-factory_bot
  - rubocop-rspec_rails

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3.1
  Exclude:
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "bin/*"
    - "vendor/**/*"
Style/AndOr:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/DocumentationMethod:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/IpAddresses:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/StringLiterals:
  ConsistentQuotesInMultiline: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded
  SupportedStyles:
    - compact
    - expanded

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringMethods:
  Enabled: true

Style/WordArray:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/routes.rb"

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Max: 30

Lint/MissingCopEnableDirective:
  Enabled: false

Layout/LineLength:
  Max: 125

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
  SupportedStylesAlignWith:
    - keyword
    - variable

RSpec/DescribeClass:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/ContextWording:
  Prefixes:
    - and
    - when
    - with
    - without
