default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: "scaminom"
  password: "root"
  timeout: 5000

development:
  <<: *default
  database: hostpital_managment_api_development

test:
  <<: *default
  database: hostpital_managment_api_test

production:
  <<: *default
  database: hostpital_managment_api_production
  username: hostpital_managment_api
  password: <%= ENV["HOSTPITAL_MANAGMENT_API_DATABASE_PASSWORD"] %>
